import { jsPDF } from "jspdf";
import type { CaseRecord } from "./storage";

export function exportCasePdf(c: CaseRecord): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(5, 10, 20);
  doc.rect(0, 0, pageWidth, 297, "F");

  doc.setTextColor(231, 236, 245);
  doc.setFontSize(22);
  doc.text("PneumoVision AI", 20, 25);

  doc.setFontSize(10);
  doc.setTextColor(90, 112, 153);
  doc.text("AI-Assisted Chest X-Ray Screening Report", 20, 33);

  doc.setDrawColor(30, 48, 84);
  doc.line(20, 38, pageWidth - 20, 38);

  doc.setFontSize(11);
  doc.setTextColor(200, 214, 232);
  let y = 50;

  const addRow = (label: string, value: string) => {
    doc.setTextColor(90, 112, 153);
    doc.text(label, 20, y);
    doc.setTextColor(231, 236, 245);
    doc.text(value, 80, y);
    y += 8;
  };

  addRow("Case ID:", c.id);
  addRow("Date:", new Date(c.date).toLocaleString());
  addRow("Patient:", c.patientName || "Not provided");
  addRow("Patient ID:", c.patientId || "—");
  addRow("Age:", c.age || "—");
  addRow("Sex:", c.sex || "—");

  y += 5;
  doc.setDrawColor(30, 48, 84);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  const isPneumonia = c.diagnosis.toLowerCase().includes("pneumonia");
  doc.setFontSize(16);
  doc.setTextColor(isPneumonia ? 255 : 0, isPneumonia ? 77 : 230, isPneumonia ? 106 : 138);
  doc.text(c.diagnosis, 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(200, 214, 232);
  addRow("Confidence:", `${(c.confidence * 100).toFixed(1)}%`);
  addRow("P(Pneumonia):", `${(c.probabilityPneumonia * 100).toFixed(1)}%`);
  addRow("P(Normal):", `${(c.probabilityNormal * 100).toFixed(1)}%`);
  addRow("Model:", c.modelVersion || "ResNet50-FT v1");

  y += 5;

  try {
    if (c.originalImage) {
      doc.addImage(c.originalImage, "PNG", 20, y, 75, 75);
    }
    if (c.heatmapImage) {
      doc.addImage(c.heatmapImage, "PNG", 105, y, 75, 75);
    }
  } catch {
    // Skip images if they fail to render
  }

  y += 85;
  doc.setFontSize(8);
  doc.setTextColor(90, 112, 153);
  doc.text(
    "DISCLAIMER: This report is generated by an AI screening tool and is not a certified medical diagnosis.",
    20,
    y,
    { maxWidth: pageWidth - 40 }
  );
  doc.text("All findings must be confirmed by a licensed clinician.", 20, y + 6);

  doc.save(`PneumoVision_${c.id}_${new Date(c.date).toISOString().slice(0, 10)}.pdf`);
}
